export const chatListDummy = [
  {
    id: 1,
    title: "109220-Naturalization",
    isGroup: true,
    time: "02/06/2021 10:45",
    message: [
      { from: "Philips", value: "Check out guys" },
      { from: "Philips", value: "P" },
      { from: "Philips", value: "P" },
      { from: "Philips", value: "P" },
      { from: "Philips", value: "P" },
      { from: "Philips", value: "P" },
      { from: "Philips", value: "P" },
    ],
  },
  {
    id: 2,
    title: "Jeannette Moraima Guaman Chamba (Hutto I-589) [ Hutto Follow Up - Brief Service ]",
    isGroup: true,
    time: "02/06/2021 10:45",
    message: [
      { from: "Ellen", value: "Check out guys" },
      { from: "Philips", value: "P" },
      { from: "Ellen", value: "P" },
      { from: "Philips", value: "P" },
      { from: "Ellen", value: "P" },
      { from: "Philips", value: "P" },
      { from: "Ellen", value: "P" },
    ],
  },
  {
    id: 3,
    title: "8405-Diana SALAZAR MUNGUIA",
    isGroup: true,
    time: "02/06/2021 10:45",
    message: [
      { from: "Cameron Phillips", value: "Check out guys" },
      { from: "Philips", value: "P" },
      { from: "Cameron Phillips", value: "P" },
      { from: "Philips", value: "P" },
      { from: "Cameron Phillips", value: "P" },
      { from: "Philips", value: "P" },
      { from: "Cameron Phillips", value: "P" },
    ],
  },
  {
    id: 4,
    title: "FastVisa Support",
    isGroup: false,
    time: "01/06/2021 12:19",
    image: "/a-icon.png",
    message: [{ from: "FastVisa Support", value: "Please pay your debt" }],
  },
];
